### ISSUE TITLE
Contract Notifications

### ISSUE THREAD

**Issue by Arrow768** [Aurorastation/Web-Interface#22]
Allow users to subscribe to contract updates that will be sent to their forum e-mail

**ToDo:**
 - [x] Add Mail Notification Class
 - [x] Add contract_subscribers table (That tracks what user is watching what contract)
 - [x] Automatically subscribe the author of the contract to the contract
 - [x] Automatically subscribe users to a contract if they post on the contract
 - [x] Add subscribe and unsubscribe buttons to the contract details page
 - [x] Change the message sent to the player/mods to include the type of the message posted.

**Comment by Arrow768** [comment]
First version of contract notifications is implemented
